services:
  web:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    restart: unless-stopped
    volumes:
      - "./src:/app/src"
      # - "/app/node_modules"
    ports:
      - 5173:5173
    env_file: .env
    command: ["npm", "run", "dev", "--watch"]